services:
  postgres:
    image: postgres:15
    container_name: postgres-db-news-app
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news_admin -d news_app_prod"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    networks:
      - backend-db-network 
  
  news_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    env_file:
      - .env.prod
    networks:
      - backend-db-network 
      - backend-frontend-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  backend-db-network:
    driver: bridge
  backend-frontend-network:
    driver: bridge
    external: true
